### PR TITLE
FHAC-115: Changed the connect webservices and common types version to release version

### PR DESCRIPTION
**Pull request by nareshcgi**
Changed the connect webservices and common types version to release version.

### CODE REVIEW

**Comment by christophermay07** [comment]
I've reviewed this PR, endorsing for merge without comments.

**Comment by alameluchidambaram** [comment]
Reviewed and looks good.

**Comment by sailajaa** [comment]
I have reviewed and good with PR

**Comment by nareshcgi** [comment]
No longer required, so closing the pull request.

**Pull request closed without merging**
