### PR TITLE
UnsecuredSecurityHeaders

### PR DESCRIPTION
**Pull request by TabassumJafri**

### CODE REVIEW

**Review by mhpnguyen — COMMENTED** [review]
Question: Why do we need jks for this test?

**Review by mhpnguyen — COMMENTED** [review]
Optional: in setup passthrough, we don't have a step to test secure adapter endpoint.  We only do unsecure for passthrough mode

**Review by sovanncgi — CHANGES_REQUESTED** [review]
For document query, please update mockdocqueryadpater response to:

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:urn="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:urn1="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:urn2="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0">
	<soap:Header/>
	<soap:Body>
		<urn:AdhocQueryResponse xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Success" requestId="1" startIndex="0" totalResultCount="0">
			<ns2:ResponseSlotList/>
		</urn:AdhocQueryResponse>
	</soap:Body>
</soap:Envelope>

**Review by sovanncgi — APPROVED** [review]
Approved for merge

**Review by mhpnguyen — APPROVED** [review]

**Pull request merged**
