### PR TITLE
FHAC-909:Update CONNECT ReadMe.md and History.md

### PR DESCRIPTION
**Pull request by danielrf123**
Update CONNECT ReadMe.md and History.md.  Added the history for releases 4.1 thru 4.6.
@mhpnguyen and @sailajaa, can you please review this PR?

### CODE REVIEW

**Comment by sailajaa** [comment]
We need to update summary of each release. I do not think its a best practice to include ticket number's, bug fixes etc. (information that was there in release notes) in History page. I would suggest to review content/ format that already there in history.md and provide summary of each release for later versions.

**Comment by sailajaa** [comment]
Reviewed 4.6 content, below are my comments:
1.In summary we need to include few lines about performance test since we did it after six releases. 
2. I would not include that total session started with " As part of the feature analysis effort..", If it needed to include briefly summarize. 
3. I would not include "Note" which is follwed after "As part of the feature analysis effort..".
4. In Bug fixes, I would not mention ticket details or cxf jar details, Instead I would brief the issue and provide summary.
5. I would brief last two paragraphs little further. ( paragraph starting with "From a product development perspective," and "Going forward beyond 4.6 - Development"

**Comment by sailajaa** [comment]
Overall, I think it need little more sentence briefing and summay of the releases not all the details. Please do a proof reading before next push.

**Comment by mhpnguyen** [comment]
Endorse for merging once comments have been addressed above

**Comment by danielrf123** [comment]
The comments above have been addressed.  There is a new push that needs reviews.

**Comment by sailajaa** [comment]
I reviewed and good with PR merge.

**Pull request merged**
