### PR TITLE
CONN-1463

### PR DESCRIPTION
**Pull request by christophermay07**
Corrected Direct and Direct-less builds for was, wasce, and weblogic
Fixed generated versions for application.xml

### CODE REVIEW

**Comment by nareshcgi** [comment]
Same comment as Alamelu, the fix should be only related to removing those jars.

**Comment by christophermay07** [comment]
Created https://connectopensource.atlassian.net/browse/CONN-1486 based on Alamelu's comments.

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Comment by alameluchidambaram** [comment]
Reviewed and good to merge the PR.

**Pull request merged**
