### PR TITLE
FHAC 1031: Fix tear down script for any jmx projects

### PR DESCRIPTION
**Pull request by mhpnguyen**
- Apply logic in teardown script to determine whether the system should switch from standard to passthrough mode.
  @TabassumJafri (optional) @danielrf123 @sailajaa : Can you please review this?

### CODE REVIEW

**Comment by sailajaa** [comment]
I reviewed PR and good with changes. It will be good if we can format tear down scripts, but leaving it for developer choice.

**Comment by mhpnguyen** [comment]
I will address format for tear down script.

**Comment by danielrf123** [comment]
I have reviewed and endorse for merge after the comment above has been addressed.

**Comment by danielrf123** [comment]
Starting the merge.

**Pull request merged**
