### PR TITLE
CONN-1583 renaming and deleting folders

### PR DESCRIPTION
**Pull request by sovanncgi**
Renamed CONN-XXXX folders in Bimodal and Manual regression test. Deleted CONN-740 and CONN-997.

### CODE REVIEW

**Comment by nareshcgi** [comment]
Please list out all the regression suites that are renamed in the description (include the original name and also the changed name).

**Comment by sovanncgi** [comment]
The following folders (listed by regression suite) were renamed:

BIMODAL:

CONN-376 > QD-serviceVersion
CONN-377 > RD-serviceVersion
CONN-443 > multispecErrorMessages
CONN-470 > adapterCountryCode
CONN-478 > adapterQDeventCodes
GW-406-949 > PD-badURL

MANUAL:

CONN-467 > WSA-to
CONN-978 > MockNwHINServices

**Comment by nareshcgi** [comment]
Can we change the name of the RegressionSuites more meaningfully:
QD-serviceVersion
RD-serviceVersion
PD-badURL
multispecErrorMessages

**Comment by nareshcgi** [comment]
Closing it, a separate pull request will be created with the ticket number.

**Pull request closed without merging**
