### PR TITLE
Fix an issue that SOAP client cannot pick up a private key specified by CLIENT_KEY_ALIAS

### PR DESCRIPTION
**Pull request by ghost**
Changes in this request fix an issue that CXF SOAP client cannot pick up a private key specified by CLIENT_KEY_ALIAS variable if there are more than two private keys in the keystore file.
SSLSocketFactory is used in org.apache.cxf.transport.https.HttpsURLConnectionFactory anyway.

### CODE REVIEW

**Comment by jsmith2** [comment]
add to whitelist

**Comment by jsmith2** [comment]
Hi Teruyuki,

Thanks for your contribution!  I've created a couple of tickets in our public JIRA for this pull request and your other pr:

https://connectopensource.atlassian.net/browse/CONN-1578
https://connectopensource.atlassian.net/browse/CONN-1579

Could you please review those tickets and add any necessary comments and/or context that is missing?

We'll update you on the status of our code review through those tickets.

Thanks,

Jason Smith
Lead Developer, CONNECT Product Team

**Comment by jsmith2** [comment]
The pull request is failing due to compilation errors at line 89:  tlsCP.setSecureRandom(new SecureRandom());

You need to add an import for SecureRandom.

**Comment by christophermay07** [comment]
Closing due to no recent activity on this PR, or the paired PR #977.

**Pull request closed without merging**
