### PR TITLE
FHAC-9:Fix MatchAlgorithm and MinimumDegreeMatch in ValidationSuite PD request...

### PR DESCRIPTION
**Pull request by alameluchidambaram**
FHAC-9:Fix MatchAlgorithm and MinimumDegreeMatch in ValidationSuite PD request.

### CODE REVIEW

**Comment by nareshcgi** [comment]
retest this please

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Comment by sailajaa** [comment]
Reviewed and good with PR.

**Comment by christophermay07** [comment]
retest this please

**Comment by christophermay07** [comment]
retest this please

**Pull request merged**
