### PR TITLE
FHAC-810: Removed unused code discovered in the Fortify 4.6 scan

### PR DESCRIPTION
**Pull request by danielrf123**
Removed unused code discovered in the Fortify 4.6 scan.

### CODE REVIEW

**Comment by christophermay07** [comment]
Don't merge this PR until #1227 is merged, and this PR is rebased on top.

**Comment by christophermay07** [comment]
I've reviewed this PR, endorsing for merge without comment.

**Comment by alameluchidambaram** [comment]
@danielrf123 : Please provide description for the PR

**Comment by mhpnguyen** [comment]
Done review. Endorsing for merging without comment except PR's description

**Pull request merged**
