### PR TITLE
SoapUI Prop Cleanup

### PR DESCRIPTION
**Pull request by christophermay07**
- Formatted XML files for consistency: XML pretty-print, no trailing spaces, four spaces for indentation, new lines at end of file
- Formatted properties files for consistency: Hash character for comments, removed hard-coded directories, new lines at end of file, removed deprecated properties
- Updated test ICI and UDDI files to be consistent with changes made to the ICI and UDDI files in CONNECT Properties module in 4.6.

### CODE REVIEW

**Comment by christophermay07** [comment]
@sailajaa @alameluchidambaram please review

**Comment by christophermay07** [comment]
Forgot to mention: don't merge until this is rebased on top of #1225

**Comment by christophermay07** [comment]
@sailajaa my answer to all of your questions so far is the same: unless the test is designed to see how our code reacts to missing endpoints, we should keep the uddi and ici files as close to the reference versions as possible.

**Comment by sailajaa** [comment]
Overall, I noticed endpoints added in existing soapui projects that are not required in bunch of files. My understanding is , we have project level ICI and UDDI files based on SoapUI project behavior (Ex. ValidateDQDRMultispec support project) and ICI,UDDI are pretty common across projects but not necessary to have all endpoints.

**Pull request closed without merging**
