### PR TITLE
Fix DQ endpoint and remove unnecessary properties

### PR DESCRIPTION
**Pull request by mhpnguyen**
- Fix DQ endpoint and remove unnecessary properties

@TabassumJafri @sailajaa: Can you please review this?

### CODE REVIEW

**Comment by sailajaa** [comment]
There are still some properties that are not required for this project. Ex: NotifySubscriptionID, SubscribePatientID, SubscriptionDB etc..

**Comment by sailajaa** [comment]
"update config" test step is not required for DQ service in both g0, g1 suites.

**Comment by TabassumJafri** [comment]
Good with merge without any comments

**Comment by sailajaa** [comment]
There are still some properties that are not being used in project. Ex: auditRepoDB,AuditRepoTable, PurposeOfDisclosure etc. . 

There are some properties at TestSuite level for PDDefReq, PDDefRes.  Need to clean-up all the un-used properties.

**Comment by sailajaa** [comment]
Reviewed PR and good with merge.

**Pull request merged**
