### PR TITLE
Modified the code to use compareClassName method in Document Retrieve Web Services Module

### PR DESCRIPTION
**Pull request by nareshcgi**
...dule

### CODE REVIEW

**Comment by whitecat** [comment]
What ever happened to CONN-625? The issue does not seem to be in the issue repository any more.

**Comment by mhpnguyen** [comment]
Thank you for using CONNECT product.  The ticket system has been moved to https://connectopensource.atlassian.net/secure/Dashboard.jspa .  Please feel free to log any issues if you have one.

**Comment by whitecat** [comment]
@mhpnguyen Thank you for the response. When I go to https://connectopensource.atlassian.net/browse/CONN-625
I only receive an error:

```
This issue can't be viewed
The issue you're trying to view can't be displayed.
It may have been deleted or you don't have permission to view it right now.
```

**Comment by mhpnguyen** [comment]
@whitecat Please create new account in order to browse or create new ones

**Pull request merged**
