### PR TITLE
4.4 Merge for 4.4.1

### PR DESCRIPTION
**Pull request by jsmith2**
Merging all post 4.4 to 4.4.1 and changing pom for 4.4.1 snapshot.

### CODE REVIEW

**Comment by christophermay07** [comment]
I've reviewed this PR, endorsing for merge without comments.

**Comment by sailajaa** [comment]
I have reviewed and good with PR merge.

**Comment by alameluchidambaram** [comment]
Reviewed PR and looks good.

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Pull request merged**
