### PR TITLE
FHAC-988-990:Regression update for DocQueryOnDemand, DQDROnDemandandStableDR projects

### PR DESCRIPTION
**Pull request by sailajaa**
1.Consolidated DocQueryOnDemand and DQDROnDemandandStableDR projects into a single project - DocQueryOnDemand.
2. Clean-up of properties that are not in use.
3. Remove "update Config", "check passthrough" scripts as they are not required.

### CODE REVIEW

**Comment by sailajaa** [comment]
@mhpnguyen @danielrf123 : PR assigned for Review.

**Comment by danielrf123** [comment]
Endorse for PR merge with no comments.

**Comment by mhpnguyen** [comment]
ok to test

**Comment by mhpnguyen** [comment]
retest this please

**Comment by mhpnguyen** [comment]
retest this please

**Comment by mhpnguyen** [comment]
Endorse for merging without comments

**Pull request merged**
