### PR TITLE
FHAC-223:Update to AuditLogging-Passthrough Regression Suite to include X12 test cases

### PR DESCRIPTION
**Pull request by sailajaa**
Update to Audit Logging-Passthrough Regression suite to Included:
1. X12 Realtime, Batch Request and Batch Response Audit Logging test cases.
2. Added checks to verify logged rows, verify audit table field information and verify XMLelements/attributes from the message field.

### CODE REVIEW

**Comment by nareshcgi** [comment]
In the Verify Message step, Audit Log XML elements/attributes field verification is missing? I see only the XML Code Attribute value is checked.

**Comment by sailajaa** [comment]
Verifying all the XML elements / attributes will be addressed in future sprints / pr's

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Comment by alameluchidambaram** [comment]
Reviewed PR and good with the merge.

**Pull request merged**
