### PR TITLE
FHAC-845: Common-Types and CONNECT-Webservices update

### PR DESCRIPTION
**Pull request by christophermay07**
Updated Common-Types and CONNECT-Webservices to 4.3.0 (release version)

### CODE REVIEW

**Comment by christophermay07** [comment]
retest this, please

**Comment by mhpnguyen** [comment]
retest this, please

**Comment by mhpnguyen** [comment]
retest this, please

**Comment by sraoonc** [comment]
Reviewed PR. Endorse for merge without comments.

**Comment by mhpnguyen** [comment]
retest this, please

**Pull request merged**
