### PR TITLE
FHAC-883:Updated ValidateAuditQueryLogService Regression Project

### PR DESCRIPTION
**Pull request by sailajaa**
1. Removed "Outcome" from ValidateAuditqueryLogService testcases.
2. Disabled Schema Compliance assertion due to schema mismatch with auditrepositary table.
   Created Ticket (FHAC-894) to address Schema compliance and null value issue in future sprints.

### CODE REVIEW

**Comment by sailajaa** [comment]
@TabassumJafri @mhpnguyen : PR assigned for Review.

**Comment by TabassumJafri** [comment]
Reviewed and good with merge.

**Comment by mhpnguyen** [comment]
Reviewed and good with merge.

**Comment by mhpnguyen** [comment]
Reviewed PR and endorse for merging

**Pull request merged**
