### PR TITLE
remove performance repository

### PR DESCRIPTION
**Pull request by bhumphrey**
There were no test for this code and it is deprecated (replaced by the event logging)

### CODE REVIEW

**Comment by jsmith2** [comment]
Need to remove the perfRepo from Product/DBScripts in nhincdb/nhincdb.sql, nhincdb/dropall.sql, perfrepo directory, and the oracle db scripts as well.

**Comment by jsmith2** [comment]
And the domain.xml (self signed) needs to be modified to remove the data source.

**Comment by bhumphrey** [comment]
There is another issue in jira for this. This pull is just to help code
coverage.

Sent from my iPhone

On Feb 24, 2013, at 11:28 AM, Jason notifications@github.com wrote:

And the domain.xml (self signed) needs to be modified to remove the data
source.

—
Reply to this email directly or view it on
GitHubhttps://github.com/CONNECT-Solution/CONNECT/pull/409#issuecomment-14010992.

**Comment by jsmith2** [comment]
I added a comment to that issue (https://issues.connectopensource.org/browse/CONN-84), that the code removal part was complete.

**Pull request merged**
