### PR TITLE
FHAC-925: update pom version to 4.7.0 snapshot for post release 4.6

### PR DESCRIPTION
**Pull request by mhpnguyen**
Update pom version to 4.7.0 snapshot release.
@christophermay07 (optional), @danielrf123 , @sailajaa : can you please review this?

### CODE REVIEW

**Comment by sailajaa** [comment]
There is a pom under //Regressionsuite/Graveyard , which got pom entry but, this pr do not have pom version update. There is no active profile for Graveyard folder, hence it need a manual pom update.

**Comment by sailajaa** [comment]
There are few projects under //RegressionSuite which are executed manually and which does not have active profile. But they have pom.xml . We need to update 4.7.0 snapshot manually in all those pom files. Example of such projects:
(ValidateQDMessageSpecVersionTest, ValidateRDMessageSpecVersionTest)

**Comment by mhpnguyen** [comment]
Update version for orphan pom

**Comment by danielrf123** [comment]
Reviewed and approved for merge after the second commit.

**Comment by sailajaa** [comment]
Need to update 4.6 and 4.6_integration branches with correct snapshot version for orphan pom.xml's.

**Comment by sailajaa** [comment]
Merging this PR with an understanding that we are going to update to 4.6 and 4.6_Integration branches with different PR's as part of this ticket. Since we do not have merge job's on that branches we may  have to create separate PR for each branch.

**Pull request merged**
