### PR TITLE
remove unused glassfish dependence

### PR DESCRIPTION
**Pull request by mhpnguyen**
Remove unused glassfish ear depedence when running soapUI validation suite.

@TabassumJafri @danielrf123 @sailajaa (optional): Can you please review this?

### CODE REVIEW

**Comment by TabassumJafri** [comment]
Endorsing for merge without any comments.

**Comment by danielrf123** [comment]
Endorse for merge with no comments.  Will merge after the checks have completed.

**Comment by mhpnguyen** [comment]
test this please

**Comment by mhpnguyen** [comment]
ok to test

**Comment by mhpnguyen** [comment]
retest this please

**Comment by mhpnguyen** [comment]
retest this please

**Pull request merged**
