### PR TITLE
CONN-1531

### PR DESCRIPTION
**Pull request by christophermay07**
Update Trust Bundle list every time the Domain Edit dialog is shown.

### CODE REVIEW

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Comment by sailajaa** [comment]
I reviewed and good with PR merge.

**Comment by alameluchidambaram** [comment]
Reviewed the PR and good with merge.

**Comment by jsmith2** [comment]
Will merge with no comments after pr validator completes.

**Pull request merged**
