### PR TITLE
CONN-1568 Update to 4.5 Snapshot

### PR DESCRIPTION
**Pull request by jsmith2**
Updated all poms with mvn versions:set to 4.5.0-SNAPSHOT,

### CODE REVIEW

**Comment by christophermay07** [comment]
The following POMs have the wrong version:
- startEmbedded (RegressionSuite)
- stopEmbedded (RegressionSuite)
- TransactionIDTest (RegressionSuite/Standard)
- Fanout-Test (RegressionSuite/Standard)
- EntitySendingXDRAsyncResponseTests (RegressionSuite/Standard)
- EntitySendingXDRAsyncReqTests (RegressionSuite/Standard)
- NHINCReceivingXDRAsyncResponseTests (RegressionSuite/Passthru)
- NHINCReceivingXDRAsyncRequestTests (RegressionSuite/Passthru)
- DocQueryErrorCodesPassthru (RegressionSuite/Passthru)
- JMXConfig (RegressionSuite/NewFeature)
- CONN-560 (RegressionSuite/NewFeature)
- CONN-891 (RegressionSuite/NewFeature)
- CONN-892 (RegressionSuite/NewFeature)
- CONN-896 (RegressionSuite/NewFeature)
- LargePayloadTest (RegressionSuite/Manual)
- Gateway-2085 (RegressionSuite/Bimodal)
- CONN-376 (RegressionSuite/Bimodal)
- CONN-377 (RegressionSuite/Bimodal)

**Comment by nareshcgi** [comment]
retest this please

**Comment by christophermay07** [comment]
I've reviewed this PR, endorsing for merge without further comment.

**Comment by nareshcgi** [comment]
Reviewed the PR and looks good.

**Pull request merged**
